'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {backend} from '../lib/admin-api';
import {contactIdentity} from '../lib/contacts';
import {type Product,type ProductCategory,type SocialLink,type Platform} from '../data/catalogue';
import {categories as initialServices,type Category} from '../data/services';
export default function AdminPanel({backendReady=false}:{backendReady?:boolean}){
 const [session,setSession]=useState<{token:string;role:string}|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('products');
 const [items,setItems]=useState<Product[]>([]),[cats,setCats]=useState<ProductCategory[]>([]),[links,setLinks]=useState<SocialLink[]>([]),[groups,setGroups]=useState<Category[]>(initialServices);
 const [edit,setEdit]=useState<Product|null>(null),[name,setName]=useState(''),[nameAr,setNameAr]=useState(''),[price,setPrice]=useState(''),[cat,setCat]=useState(''),[description,setDescription]=useState(''),[descriptionAr,setDescriptionAr]=useState(''),[image,setImage]=useState<File|null>(null),[published,setPublished]=useState(false);
 const [categoryEdit,setCategoryEdit]=useState<ProductCategory|null>(null),[categoryName,setCategoryName]=useState(''),[categoryAr,setCategoryAr]=useState('');
 const [linkEdit,setLinkEdit]=useState<SocialLink|null>(null),[platform,setPlatform]=useState<Platform>('whatsapp'),[address,setAddress]=useState('');
 const load=async(token:string)=>{const [p,c,l,g]=await Promise.all(['products?order=created_at.desc','product_categories?order=created_at.asc','social_links?order=created_at.asc','service_groups?order=created_at.asc'].map(t=>backend('/data/'+t,token)));setItems(p);setCats(c);setLinks(l);setGroups(initialServices.map(group=>g.find((v:Category)=>v.id===group.id)||group));};
 const run=async(action:()=>Promise<void>,success='Enregistré. Le site public affichera la modification à son prochain chargement.')=>{setBusy(true);setNotice('');try{await action();setNotice(success)}catch(e){setNotice(e instanceof Error?e.message:'Une erreur est survenue.')}finally{setBusy(false)}};
 const save=async(table:string,id:string|null,value:unknown)=>{if(!session)throw new Error('Connexion requise.');const result=await backend('/data/'+table+(id?'?id=eq.'+encodeURIComponent(id):''),session.token,{method:id?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(value)});if(!result?.length)throw new Error('Modification refusée ou élément introuvable.');return result;};
 const [uploadVersion,setUploadVersion]=useState(0);
 useEffect(()=>{if(!backendReady)return;let mounted=true;void backend('/auth/session',null).then(async result=>{await load('session');if(mounted)setSession({token:'session',role:result.role});}).catch(()=>{});return()=>{mounted=false};},[backendReady]);
 const resetProduct=()=>{setUploadVersion(v=>v+1);setEdit(null);setName('');setNameAr('');setPrice('');setDescription('');setDescriptionAr('');setImage(null);setPublished(false);setCat('')};
 const openProduct=(p:Product)=>{setEdit(p);setName(p.name.fr);setNameAr(p.name.ar);setPrice(String(p.price??''));setDescription(p.description?.fr||'');setDescriptionAr(p.description?.ar||'');setImage(null);setPublished(p.status==='published');setCat(p.category_id);window.scrollTo({top:0,behavior:'smooth'})};
 const submitProduct=(e:FormEvent)=>{e.preventDefault();void run(async()=>{if(!session)return;let src=edit?.image;if(image){if(!['image/jpeg','image/png','image/webp'].includes(image.type)||image.size>5*1024*1024)throw new Error('Choisissez une image JPG, PNG ou WebP de moins de 5 Mo.');const uploaded=await backend('/uploads',session.token,{method:'POST',headers:{'Content-Type':image.type},body:image});src=uploaded.url;}if(!src)throw new Error('Ajoutez une photo du produit.');if(!name.trim()||!Number.isFinite(Number(price))||Number(price)<0||!price)throw new Error('Un nom et un prix valide sont requis.');await save('products',edit?.id||null,{name:{fr:name.trim(),ar:nameAr.trim()||name.trim()},price:Number(price),category_id:cat||cats[0]?.id,description:{fr:description.trim(),ar:descriptionAr.trim()},image:src,status:published?'published':'draft'});await load(session.token);resetProduct()})};
 if(!backendReady)return <main className="admin-panel"><Link href="/fr">← OHH ZAZ</Link><h1>Administration</h1><p className="admin-notice">La connexion sécurisée n’est pas encore configurée. Aucun compte ni enregistrement local simulé n’est activé.</p><p>Le déploiement doit connecter PostgreSQL sur Railway et appliquer les permissions Admin / Manager décrites dans le guide de mise en service.</p></main>;
 if(!session)return <main className="admin-panel"><Link href="/fr">← OHH ZAZ</Link><h1>Votre espace salon.</h1><p>Connexion réservée aux comptes invités par le propriétaire.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{const result=await backend('/auth/login',null,{method:'POST',body:JSON.stringify({email,password})});await load('session');setSession({token:'session',role:result.role});setPassword('')},'Connexion établie.')}}><label>E-mail<input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mot de passe<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy} className="button">{busy?'Connexion…':'Se connecter'}</button></form><p role="status">{notice}</p></main>;
 return <main className="admin-panel"><Link href="/fr" target="_blank">Voir le site ↗</Link><h1>Le salon, à jour.</h1><p>{session.role==='admin'?'Administrateur':'Manager'} · Session sécurisée de 8 heures. Déconnectez-vous sur un appareil partagé.</p><button className="text-link" onClick={()=>void run(async()=>{try{await backend('/auth/logout',session.token,{method:'POST'})}finally{setSession(null)}},'Déconnexion effectuée.')}>Se déconnecter</button><div className="admin-tabs">{[['products','Produits'],['categories','Catégories'],['services','Tarifs'],...(session.role==='admin'?[['contacts','Contacts & réseaux']]:[])].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setNotice('')}}>{label}</button>)}</div><p role="status" className="admin-status">{busy?'Enregistrement en cours…':notice}</p>
 {tab==='products'&&<><h2>{edit?'Modifier le produit':'Créer un produit'}</h2><form onSubmit={submitProduct}><label>Photo {edit?'(facultatif pour conserver la photo)':''}<input key={`${edit?.id||'new'}-${uploadVersion}`} type="file" accept="image/jpeg,image/png,image/webp" required={!edit} onChange={e=>setImage(e.target.files?.[0]||null)}/></label><div className="admin-pair"><label>Nom<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Nom arabe (facultatif)<input dir="rtl" maxLength={160} value={nameAr} onChange={e=>setNameAr(e.target.value)}/></label></div><div className="admin-pair"><label>Prix en DH<input required type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Catégorie<select required value={cat||cats[0]?.id||''} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c.id} value={c.id}>{c.name.fr}</option>)}</select></label></div><details><summary>Ajouter une description (facultatif)</summary><label>Description française<textarea maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Description arabe<textarea dir="rtl" maxLength={2000} value={descriptionAr} onChange={e=>setDescriptionAr(e.target.value)}/></label></details><label className="inline-field"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>Afficher sur le site</label><button disabled={busy||!cats.length} className="button">{edit?'Enregistrer les modifications':'Créer le produit'}</button>{edit&&<button type="button" onClick={resetProduct}>Annuler</button>}</form><div className="admin-list">{items.map(p=><div className="admin-row" key={p.id}><span>{p.name.fr} · {p.price} DH · {p.status==='published'?'Visible':'Brouillon'}</span><button onClick={()=>openProduct(p)}>Modifier</button></div>)}</div></>}
 {tab==='categories'&&<><h2>{categoryEdit?'Modifier la catégorie':'Nouvelle catégorie'}</h2><form onSubmit={e=>{e.preventDefault();void run(async()=>{await save('product_categories',categoryEdit?.id||null,{name:{fr:categoryName.trim(),ar:categoryAr.trim()||categoryName.trim()}});await load(session.token);setCategoryEdit(null);setCategoryName('');setCategoryAr('')})}}><label>Nom<input required value={categoryName} onChange={e=>setCategoryName(e.target.value)}/></label><label>Nom arabe (facultatif)<input value={categoryAr} onChange={e=>setCategoryAr(e.target.value)}/></label><button className="button" disabled={busy}>Enregistrer la catégorie</button></form><div className="admin-list">{cats.map(c=><div className="admin-row" key={c.id}><span>{c.name.fr} / {c.name.ar}</span><button onClick={()=>{setCategoryEdit(c);setCategoryName(c.name.fr);setCategoryAr(c.name.ar)}}>Modifier</button></div>)}</div></>}
 {tab==='contacts'&&session.role==='admin'&&<><h2>{linkEdit?'Modifier le compte':'Ajouter un compte'}</h2><p>Un compte ouvre directement son lien. Plusieurs comptes ouvrent un choix avec leurs identifiants.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{let url=address.trim();if(platform==='whatsapp'&&!url.startsWith('https://')){let digits=url.replace(/\D/g,'');if(digits.startsWith('0'))digits='212'+digits.slice(1);url='https://wa.me/'+digits;}const link={id:'new',platform,url};if(!contactIdentity(link))throw new Error('Lien de profil invalide. Utilisez un profil Instagram/TikTok HTTPS, ou un numéro WhatsApp international.');const clean=new URL(url);clean.search='';clean.hash='';await save('social_links',linkEdit?.id||null,{platform,url:clean.href});await load(session.token);setLinkEdit(null);setAddress('')})}}><label>Plateforme<select value={platform} onChange={e=>setPlatform(e.target.value as Platform)}><option value="whatsapp">WhatsApp</option><option value="instagram">Instagram</option><option value="tiktok">TikTok</option></select></label><label>Lien du profil ou numéro WhatsApp<input required value={address} onChange={e=>setAddress(e.target.value)}/></label><button className="button" disabled={busy}>Enregistrer le compte</button></form><div className="admin-list">{links.map(l=><div className="admin-row" key={l.id}><span>{l.platform} · {contactIdentity(l)}</span><button onClick={()=>{setLinkEdit(l);setPlatform(l.platform);setAddress(l.url)}}>Modifier</button><button disabled={busy} onClick={()=>{if(confirm('Retirer ce compte des liens publics ?'))void run(async()=>{await backend('/data/social_links?id=eq.'+encodeURIComponent(l.id),session.token,{method:'DELETE',headers:{Prefer:'return=representation'}});await load(session.token)})}}>Retirer</button></div>)}</div></>}
 {tab==='services'&&<><h2>Services & tarifs</h2><p>La liste initiale reprend Tarifs.pdf. Enregistrez chaque catégorie après modification.</p>{groups.map((g,gi)=><form key={g.id} onSubmit={e=>{e.preventDefault();void run(async()=>{await backend('/data/service_groups',session.token,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(g)});await load(session.token)})}}><h3>{g.fr}</h3>{g.items.map((service,si)=><div key={si} className="admin-pair"><label>Service<input required value={service.fr} onChange={e=>setGroups(all=>all.map((v,i)=>i!==gi?v:{...v,items:v.items.map((s,j)=>j!==si?s:{...s,fr:e.target.value})}))}/></label><label>العربية<input required dir="rtl" value={service.ar} onChange={e=>setGroups(all=>all.map((v,i)=>i!==gi?v:{...v,items:v.items.map((s,j)=>j!==si?s:{...s,ar:e.target.value})}))}/></label><label>Prix (DH)<input type="number" required min="0" step="0.01" value={service.price} onChange={e=>setGroups(all=>all.map((v,i)=>i!==gi?v:{...v,items:v.items.map((s,j)=>j!==si?s:{...s,price:Number(e.target.value)})}))}/></label><label className="inline-field"><input type="checkbox" checked={!!service.from} onChange={e=>setGroups(all=>all.map((v,i)=>i!==gi?v:{...v,items:v.items.map((s,j)=>j!==si?s:{...s,from:e.target.checked})}))}/>À partir de</label></div>)}<button type="button" onClick={()=>setGroups(all=>all.map((v,i)=>i!==gi?v:{...v,items:[...v.items,{fr:'',ar:'',price:0}]}))}>Ajouter une prestation</button><button disabled={busy} className="button">Enregistrer {g.fr}</button></form>)}</>}
 </main>;
}
