'use client';
import Link from 'next/link';
import {useState,useRef,useEffect} from 'react';
import {ArrowUpRight,ArrowDown,Check,Copy} from 'lucide-react';
import BridalPortrait from './BridalPortrait';
import Reveal from './Reveal';

function Spark({className=''}:{className?:string}){return <svg className={`bridal-spark ${className}`} viewBox="0 0 40 40" aria-hidden="true"><path d="M20 0C22 14 26 18 40 20C26 22 22 26 20 40C18 26 14 22 0 20C14 18 18 14 20 0Z" fill="currentColor"/></svg>}
const stories=[
 {image:'bridal-updo',fr:'La coiffure',ar:'التسريحة',titleFr:'La coiffure, avec votre tenue.',titleAr:'حركة ناعمة. بصمتكِ.',bodyFr:'Une attache délicate, du volume ou des longueurs libres. Partagez vos inspirations, votre tenue et vos accessoires pour imaginer l’ensemble avec Siham.',bodyAr:'رفعة ناعمة، حجم أو خصلات منسدلة. شاركي صور إلهامكِ وإطلالتكِ وإكسسواراتكِ لتتخيّلي التفاصيل مع سهام.',altFr:'Chignon de cérémonie avec accessoires floraux, archive du salon',altAr:'رفعة شعر لمناسبة مع إكسسوارات زهرية من أرشيف الصالون'},
 {image:'bridal-makeup-stock',fr:'Le maquillage',ar:'المكياج',titleFr:'Le maquillage, selon vos envies.',titleAr:'جمالكِ، كما تحبّينه.',bodyFr:'Teint lumineux, regard soutenu ou lèvres dessinées : montrez vos inspirations à Siham, ainsi que les effets que vous préférez éviter.',bodyAr:'نظرة، إشراقة ولون. أخبرينا بما تحبّينه وما تفضّلين تجنّبه. من هذا الحوار تبدأ إطلالتكِ.',altFr:'Inspiration : portrait de mariée et maquillage lumineux',altAr:'صورة إلهام: بورتريه عروس بمكياج مضيء'},
 {image:'bridal-details-stock',fr:'Les détails',ar:'التفاصيل',titleFr:'Voile, bijoux et finitions.',titleAr:'تفاصيل تبقى في الذاكرة.',bodyFr:'Apportez une photo du voile, des bijoux et du décolleté de votre tenue. Ces éléments aident à discuter de la coiffure et des finitions.',bodyAr:'زينة للشعر، ملمس خصلة وتناسق الإطلالة. شاركي التفاصيل التي تهمّكِ، فهي ما يمنح لحظتكِ طابعها الخاص.',altFr:'Inspiration : perles, voile de dentelle et manucure de mariée',altAr:'صورة إلهام: لؤلؤ وطرحة دانتيل وأظافر العروس'}
];
export default function BridalExperience({locale,full=false}:{locale:'fr'|'ar';full?:boolean}){
 const ar=locale==='ar';const [vertical,setVertical]=useState(true);const [active,setActive]=useState(0);const [checked,setChecked]=useState<number[]>([]);const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);const brief=useRef<HTMLTextAreaElement>(null);const current=stories[active];
 useEffect(()=>{const screen=matchMedia('(min-width:1001px)');const update=()=>setVertical(screen.matches);update();screen.addEventListener('change',update);return()=>screen.removeEventListener('change',update)},[]);
 useEffect(()=>{const value=Number(new URLSearchParams(location.search).get('inspiration'));if(Number.isInteger(value)&&value>=0&&value<3)setActive(value)},[locale]);
 const selectInspiration=(index:number)=>{setActive(index);const url=new URL(location.href);url.searchParams.set('inspiration',String(index));history.replaceState(null,'',url)};
 const prompts=ar?['التاريخ والتوقيت المقترحان','صور الإلهام والإكسسوارات','الخدمات التي أرغب فيها']:['Ma date et l’horaire envisagé','Mes inspirations et accessoires','Les prestations souhaitées'];
 const message=ar?'مرحباً سهام، أرغب في الحديث عن إطلالتي كعروس.\nالتاريخ والتوقيت المقترحان: …\nالخدمات المطلوبة: …\nإلهامي وإكسسواراتي: …':'Bonjour Siham, j’aimerais échanger sur ma mise en beauté mariée.\nDate et horaire envisagés : …\nPrestations souhaitées : …\nMes inspirations et accessoires : …';
 return <>
 <section className={`bridal-editorial ${full?'is-full':'is-teaser'}`} data-scroll-key="bridal">
  <div className="bridal-orbit" aria-hidden="true"/><Spark className="spark-one"/><Spark className="spark-two"/>
  <Reveal className="bridal-editorial-copy"><p className="eyebrow">{ar?'سهام · لحظتكِ الأجمل':'SIHAM · VOTRE PLUS BEAU OUI'}</p>{full?<h1>{ar?<>أنتِ،<br/><em>ولا أحد سواكِ.</em></>:<>Vous.<br/><em>Et personne d’autre.</em></>}</h1>:<h2>{ar?<>أنتِ،<br/><em>بإطلالة لا تُنسى.</em></>:<>Vous, en<br/><em>inoubliable.</em></>}</h2>}<p className="bridal-lead">{ar?'جمال يشبهكِ، حتى أدقّ التفاصيل. لنتخيّل معاً الإطلالة التي ستحكين بها قصّتكِ.':'Une beauté qui vous ressemble, jusque dans les détails. Imaginons ensemble l’allure qui racontera votre histoire.'}</p><Link className="button" href={`/${locale}/${full?'contact':'mariee'}`}>{ar?(full?'لنتخيّل إطلالتي':'اكتشفي عالم العروس'):(full?'Imaginer ma mise en beauté':'Découvrir l’univers mariée')}<ArrowUpRight size={18}/></Link>{full&&<a className="bridal-explore" href="#inspirations">{ar?'أتصفّح الإلهام':'Feuilleter les inspirations'}<ArrowDown size={15}/></a>}<span className="bridal-handwriting">{ar?'للحظات التي تبقى.':'Pour les instants qui restent.'}</span></Reveal>
  <Reveal className="bridal-editorial-visual" delay={150}><div className="bridal-portrait-frame"><BridalPortrait locale={locale} hero={full}/></div><span className="portrait-caption">OHH ZAZ · {ar?'إلهام العروس':'L’INSPIRATION MARIÉE'}</span><figure className="bridal-detail-print"><img src="/media/bridal-updo.webp" width="480" height="640" alt={ar?'تفاصيل رفعة شعر مع زينة زهرية':'Détail d’un chignon et de son bijou floral'} loading="lazy"/><figcaption>{ar?'كل تفصيل، لكِ.':'Chaque détail, pour vous.'}</figcaption></figure></Reveal>
 </section>
 {full&&<>
  <section className="bridal-album section" id="inspirations" data-scroll-key="bridal-inspirations"><Reveal className="album-heading"><p className="eyebrow">{ar?'دفتر الإلهام':'LE CARNET D’INSPIRATIONS'}</p><h2>{ar?'إطلالة واحدة. ألف تفصيل.':<>Une allure.<br/><em>Mille nuances.</em></>}</h2><p>{ar?'أعمال من الصالون وصور للإلهام، لتتخيّلي ما يشبهكِ.':'Créations de la maison et images d’inspiration : un carnet pour affiner vos envies.'}</p></Reveal><div className="album-layout"><div className="album-choices" role="tablist" aria-label={ar?'إلهام العروس':'Inspirations mariée'} aria-orientation={vertical?'vertical':'horizontal'}>{stories.map((s,i)=><button role="tab" id={`inspiration-tab-${i}`} aria-controls="inspiration-panel" aria-selected={active===i} tabIndex={active===i?0:-1} key={s.image} onClick={()=>selectInspiration(i)} onKeyDown={e=>{if(['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(active+((e.key==='ArrowDown'||e.key===(ar?'ArrowLeft':'ArrowRight'))?1:2))%3;selectInspiration(n);document.getElementById(`inspiration-tab-${n}`)?.focus()}}}><span>0{i+1}</span><span>{ar?s.ar:s.fr}</span><ArrowUpRight size={22}/></button>)}</div><div className="album-panel" id="inspiration-panel" role="tabpanel" aria-labelledby={`inspiration-tab-${active}`} tabIndex={0}><figure key={current.image}><img src={`/media/${current.image}.webp`} alt={ar?current.altAr:current.altFr} width="800" height="1000" loading="lazy"/><figcaption>OHH ZAZ · {active===0?(ar?'من أرشيف الدار':'ARCHIVES DE LA MAISON'):(ar?'صورة للإلهام · ليست من أعمال الصالون':'IMAGE D’INSPIRATION · HORS RÉALISATIONS DU SALON')}</figcaption></figure><div className="album-story" key={current.fr}><Spark/><h3>{ar?current.titleAr:current.titleFr}</h3><p>{ar?current.bodyAr:current.bodyFr}</p><Link className="text-link" href={`/${locale}/contact`}>{ar?'أشارك رغباتي':'Partager mes envies'}<ArrowUpRight size={17}/></Link></div></div></div></section>
  <section className="bridal-preparation section" data-scroll-key="bridal-preparation"><Reveal className="preparation-intro"><p className="eyebrow">{ar?'قبل أن نبدأ':'AVANT LE PREMIER ÉCHANGE'}</p><h2>{ar?'لنبدأ بكِ.':<>Tout commence<br/><em>par vous.</em></>}</h2><p>{ar?'ثلاثة أشياء بسيطة لتحضير حديثكِ مع سهام. حدّدي ما جهّزتِه، ثم انسخي رسالتكِ وأكمليها عند التواصل.':'Trois petites choses pour préparer votre échange avec Siham. Cochez ce que vous avez réuni, puis copiez ce message à compléter lors de votre prise de contact.'}</p></Reveal><div className="preparation-card"><div className="preparation-progress"><span>{ar?'دفتر لحظتي':'MON CARNET MARIÉE'}</span><bdi>{checked.length} / 3</bdi></div>{prompts.map((p,i)=><label className="preparation-check" key={p}><input type="checkbox" checked={checked.includes(i)} onChange={()=>setChecked(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])}/><span className="check-mark" aria-hidden="true">{checked.includes(i)&&<Check size={15}/>}</span><span>{p}</span></label>)}<div className="preparation-actions"><button className="button" onClick={async()=>{try{await navigator.clipboard.writeText(message);setCopied(true);setCopyError(false)}catch{setCopyError(true)}}}>{copied?(ar?'تم نسخ الرسالة':'Message copié'):(ar?'أنسخ رسالتي':'Copier mon message')}{copied?<Check size={17}/>:<Copy size={17}/>}</button><Link className="text-link" href={`/${locale}/contact`}>{ar?'أتواصل مع سهام':'Échanger avec Siham'}<ArrowUpRight size={17}/></Link></div><p className="preparation-status" role="status">{copied?(ar?'أكملي التفاصيل وأرسلي الرسالة خلال تواصلكِ. لم يتم إرسال أي شيء.':'Complétez les détails et partagez le message lors de votre échange. Rien n’a été envoyé.'):(ar?'هذه الخطوة تحضّر الحديث ولا تؤكّد حجزاً.':'Ce carnet prépare votre échange et ne confirme pas de réservation.')}</p>{copyError&&<textarea ref={brief} className="brief-fallback" readOnly aria-label={ar?'رسالة للنسخ':'Message à copier'} value={message} onFocus={e=>e.target.select()}/>}</div></section>
 </>}
 </>;
}

