'use client';
import {useRef,useEffect,useState} from 'react';
import {Play,Pause,Maximize,RotateCcw} from 'lucide-react';
const stamp=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export default function BridalFilm({locale}:{locale:'fr'|'ar'}){
 const ar=locale==='ar';const ref=useRef<HTMLVideoElement>(null),frame=useRef<HTMLDivElement>(null);const [playing,setPlaying]=useState(false),[started,setStarted]=useState(false),[ended,setEnded]=useState(false),[elapsed,setElapsed]=useState(0),[duration,setDuration]=useState(33.23),[enhanced,setEnhanced]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setEnhanced(true);const el=ref.current;if(!el)return;const observer=new IntersectionObserver(([e])=>{if(!e.isIntersecting)el.pause()});observer.observe(el);const pause=()=>{if(document.hidden)el.pause()};document.addEventListener('visibilitychange',pause);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',pause)}},[]);
 const toggle=async()=>{const el=ref.current;if(!el)return;if(!el.paused){el.pause();return}try{if(el.ended)el.currentTime=0;await el.play();setStarted(true);setEnded(false);setError('')}catch{setError(ar?'تعذّر التشغيل. حاولي مرة أخرى.':'Lecture indisponible. Réessayez.')}};
 return <div className={`bridal-film-frame ${playing?'is-playing':''}`} ref={frame}><div className="bridal-screen"><video ref={ref} controls={!enhanced} playsInline muted preload="none" poster="/media/bridal-film-poster.webp" width="576" height="1024" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{setEnded(true);setPlaying(false)}} onTimeUpdate={e=>setElapsed(e.currentTarget.currentTime)} onLoadedMetadata={e=>setDuration(e.currentTarget.duration)} onError={()=>setError(ar?'تعذّر تحميل الفيلم.':'Le film n’a pas pu être chargé.')} aria-label={ar?'فيلم تحضير العروس في الصالون، بدون صوت':'Film de préparation mariée au salon, sans son'}><source src="/media/bridal-film.mp4" type="video/mp4"/></video>{enhanced&&(!started||ended)&&<button className="bridal-play-cover" onClick={toggle} aria-label={ar?'شغّلي فيلم العروس':'Lire le film mariée'}><span className="bridal-play-ring">{ended?<RotateCcw size={28}/>:<Play size={29} fill="currentColor"/>}</span><span className="bridal-cover-caption"><small>OHH ZAZ · SIHAM</small><strong>{ar?'من أول لمسة، إلى لحظة نعم.':'Des premiers gestes au grand oui.'}</strong><span>{ar?'شغّلي الفيلم · ٣٣ ثانية':'LIRE LE FILM · 33 SECONDES'}</span></span></button>}</div>{enhanced&&<div className="bridal-player-controls"><button onClick={toggle} aria-label={playing?(ar?'إيقاف مؤقت':'Mettre le film en pause'):(ar?'تشغيل':'Lire le film')}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><bdi className="film-time">{stamp(elapsed)}</bdi><input type="range" min="0" max={duration} step="0.1" value={elapsed} aria-label={ar?'موضع تشغيل الفيلم':'Position dans le film'} aria-valuetext={`${stamp(elapsed)} / ${stamp(duration)}`} onChange={e=>{const el=ref.current;if(el&&el.readyState>0){el.currentTime=Number(e.target.value);setElapsed(el.currentTime)}}}/><bdi className="film-time">{stamp(duration)}</bdi><button aria-label={ar?'عرض كامل الشاشة':'Afficher le film en plein écran'} onClick={async()=>{try{if(frame.current?.requestFullscreen)await frame.current.requestFullscreen();else{const el=ref.current as HTMLVideoElement&{webkitEnterFullscreen?:()=>void};if(el?.webkitEnterFullscreen)el.webkitEnterFullscreen();else setError(ar?'العرض الكامل غير متاح في هذا المتصفح.':'Le plein écran n’est pas disponible dans ce navigateur.')}}catch{setError(ar?'العرض الكامل غير متاح في هذا المتصفح.':'Le plein écran n’est pas disponible dans ce navigateur.')}}}><Maximize size={18}/></button></div>}<p className="bridal-film-caption">{ar?'من التحضير إلى الإطلالة · فيلم بدون صوت':'De la préparation à l’allure · film sans son'}</p>{error&&<p role="status">{error}</p>}</div>;
}
