'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {ArrowUpRight,ArrowDown} from 'lucide-react';
import BridalPortrait from './BridalPortrait';
import BridalFilm from './BridalFilm';
import BridalPlanner from './BridalPlanner';
import Reveal from './Reveal';

function Spark({className=''}:{className?:string}){return <svg className={`bridal-spark ${className}`} viewBox="0 0 40 40" aria-hidden="true"><path d="M20 0C22 14 26 18 40 20C26 22 22 26 20 40C18 26 14 22 0 20C14 18 18 14 20 0Z" fill="currentColor"/></svg>}
const stories=[
 {image:'bridal-modern-updo',fr:'La coiffure',ar:'التسريحة',titleFr:'La coiffure, avec votre tenue.',titleAr:'حركة ناعمة. بصمتكِ.',bodyFr:'Une nuque dégagée, une ligne nette, une attache sculptée. La coiffure trouve son équilibre avec votre tenue.',bodyAr:'رفعة ناعمة، حجم أو خصلات منسدلة. شاركي صور إلهامكِ وإطلالتكِ وإكسسواراتكِ لتتخيّلي التفاصيل مع سهام.',altFr:'Chignon bas lisse avec un bijou doré et des perles',altAr:'رفعة شعر منخفضة بخصلات ناعمة'},
 {image:'bridal-modern-makeup',fr:'Le maquillage',ar:'المكياج',titleFr:'Le maquillage, selon vos envies.',titleAr:'جمالكِ، كما تحبّينه.',bodyFr:'Une peau lumineuse, des tons fondus, un regard défini. Choisissez avec Siham l’intensité qui vous ressemble.',bodyAr:'نظرة، إشراقة ولون. أخبرينا بما تحبّينه وما تفضّلين تجنّبه. من هذا الحوار تبدأ إطلالتكِ.',altFr:'Inspiration : portrait de mariée et maquillage lumineux',altAr:'صورة إلهام: بورتريه عروس بمكياج مضيء'},
 {image:'bridal-details-stock',fr:'Les détails',ar:'التفاصيل',titleFr:'Voile, bijoux et finitions.',titleAr:'تفاصيل تبقى في الذاكرة.',bodyFr:'Le mouvement du voile, l’éclat d’une boucle, une main délicate. Pensez votre beauté dans son ensemble.',bodyAr:'زينة للشعر، ملمس خصلة وتناسق الإطلالة. شاركي التفاصيل التي تهمّكِ، فهي ما يمنح لحظتكِ طابعها الخاص.',altFr:'Inspiration : perles, voile de dentelle et manucure de mariée',altAr:'صورة إلهام: لؤلؤ وطرحة دانتيل وأظافر العروس'}
];
export default function BridalExperience({locale,full=false}:{locale:'fr'|'ar';full?:boolean}){
 const ar=locale==='ar';const [active,setActive]=useState(0);const current=stories[active];
 useEffect(()=>{const value=Number(new URLSearchParams(location.search).get('inspiration'));if(Number.isInteger(value)&&value>=0&&value<3)setActive(value)},[locale]);
 const selectInspiration=(index:number)=>{setActive(index);const url=new URL(location.href);url.searchParams.set('inspiration',String(index));history.replaceState(null,'',url)};
 return <>
 <section className={`bridal-editorial ${full?'is-full':'is-teaser'}`} data-scroll-key="bridal">
  <div className="bridal-orbit" aria-hidden="true"/><Spark className="spark-one"/><Spark className="spark-two"/>
  <Reveal className="bridal-editorial-copy"><p className="eyebrow">{ar?'سهام · لحظتكِ الأجمل':'SIHAM · VOTRE PLUS BEAU OUI'}</p>{full?<h1>{ar?<>أنتِ،<br/><em>ولا أحد سواكِ.</em></>:<>Vous.<br/><em>Et personne d’autre.</em></>}</h1>:<h2>{ar?<>أنتِ،<br/><em>بإطلالة لا تُنسى.</em></>:<>Vous, en<br/><em>inoubliable.</em></>}</h2>}<p className="bridal-lead">{ar?'جمال يشبهكِ، حتى أدقّ التفاصيل. لنتخيّل معاً الإطلالة التي ستحكين بها قصّتكِ.':'Une beauté qui vous ressemble, jusque dans les détails. Imaginons ensemble l’allure qui racontera votre histoire.'}</p><Link className="button" href={full?'#carnet':`/${locale}/mariee`}>{ar?(full?'لنتخيّل إطلالتي':'اكتشفي عالم العروس'):(full?'Imaginer ma mise en beauté':'Découvrir l’univers mariée')}<ArrowUpRight size={18}/></Link>{full&&<a className="bridal-explore" href="#inspirations">{ar?'أتصفّح الإلهام':'Feuilleter les inspirations'}<ArrowDown size={15}/></a>}<span className="bridal-handwriting">{ar?'للحظات التي تبقى.':'Pour les instants qui restent.'}</span></Reveal>
  <Reveal className="bridal-editorial-visual bridal-film-visual" delay={150}><BridalFilm locale={locale}/><div className="bridal-memory-strip"><figure><BridalPortrait locale={locale}/><figcaption>{ar?'إطلالة بتوقيع سهام':'Une allure signée Siham'}</figcaption></figure><figure><img src="/media/bridal-updo.webp" width="480" height="640" alt={ar?'تفاصيل رفعة شعر زهرية':'Détail d’un chignon fleuri'} loading="lazy"/><figcaption>{ar?'التفاصيل التي تكمل الإطلالة':'Le sens du détail'}</figcaption></figure></div></Reveal>
 </section>
 {full&&<>
  <section className="bridal-journey section" aria-labelledby="journey-title"><div className="journey-title"><p className="eyebrow">{ar?'قبل اللحظة الكبيرة':'AVANT LE GRAND MOMENT'}</p><h2 id="journey-title">{ar?'إطلالتكِ تبدأ بالحوار.':<>Votre allure commence<br/><em>par une conversation.</em></>}</h2></div><div className="journey-steps">{[
 {fr:'Ce qui vous ressemble',ar:'ما يشبهكِ',bodyFr:'Une photo, une couleur, une envie. Rassemblez vos inspirations et ce que vous ne souhaitez pas.',bodyAr:'صورة، لون أو فكرة. اجمعي ما يعجبكِ وما تفضّلين تجنّبه.',href:'#inspirations',actionFr:'Explorer les nuances',actionAr:'اكتشفي التفاصيل'},
 {fr:'Chaque détail compte',ar:'كل تفصيل مهم',bodyFr:'La tenue, le voile, les bijoux : imaginez la coiffure et le maquillage dans leur ensemble.',bodyAr:'اللباس والطرحة والمجوهرات: تخيّلي الشعر والمكياج كإطلالة متكاملة.',href:'#carnet',actionFr:'Composer mon carnet',actionAr:'أحضّر دفتري'},
 {fr:'Le temps de votre jour',ar:'توقيت يومكِ',bodyFr:'Précisez l’heure à laquelle vous devez être prête. Siham confirme avec vous les prestations et la disponibilité.',bodyAr:'حدّدي وقت استعدادكِ. تؤكّد معكِ سهام الخدمات والتوفّر.',href:'#carnet',actionFr:'Préparer mon échange',actionAr:'أحضّر رسالتي'}
 ].map((step,i)=><Reveal key={step.fr} className="journey-step" delay={i*90}><span className="journey-number">0{i+1}</span><h3>{ar?step.ar:step.fr}</h3><p>{ar?step.bodyAr:step.bodyFr}</p><a className="text-link" href={step.href}>{ar?step.actionAr:step.actionFr}<ArrowUpRight size={16}/></a></Reveal>)}</div></section>
  <section className="bridal-album section" id="inspirations" data-scroll-key="bridal-inspirations"><Reveal className="album-heading"><p className="eyebrow">{ar?'دفتر الإلهام':'LE CARNET D’INSPIRATIONS'}</p><h2>{ar?'إطلالة واحدة. ألف تفصيل.':<>Une allure.<br/><em>Mille nuances.</em></>}</h2><p>{ar?'خصلات ناعمة، بشرة مضيئة وتفاصيل تختارينها. تصفّحي ما يلهمكِ.':'Une attache, une lumière, un détail. Explorez ce qui vous ressemble.'}</p></Reveal><div className="album-layout"><div className="album-choices" role="tablist" aria-label={ar?'إلهام العروس':'Inspirations mariée'} aria-orientation="horizontal">{stories.map((s,i)=><button role="tab" id={`inspiration-tab-${i}`} aria-controls="inspiration-panel" aria-selected={active===i} tabIndex={active===i?0:-1} key={s.image} onClick={()=>selectInspiration(i)} onKeyDown={e=>{if(['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(active+((e.key==='ArrowDown'||e.key===(ar?'ArrowLeft':'ArrowRight'))?1:2))%3;selectInspiration(n);document.getElementById(`inspiration-tab-${n}`)?.focus()}}}><img src={`/media/${s.image}.webp`} alt="" width="240" height="300" loading="lazy"/><span className="album-choice-label"><small>0{i+1}</small><span>{ar?s.ar:s.fr}</span><ArrowUpRight size={20}/></span></button>)}</div><div className="album-panel" id="inspiration-panel" role="tabpanel" aria-labelledby={`inspiration-tab-${active}`} tabIndex={0}><figure key={current.image}><img src={`/media/${current.image}.webp`} alt={ar?current.altAr:current.altFr} width="800" height="1000" loading="lazy"/><figcaption>{ar?'إلهام العروس':'INSPIRATION MARIÉE'} <span>0{active+1} / 03</span></figcaption></figure><div className="album-story" key={current.fr}><Spark/><h3>{ar?current.titleAr:current.titleFr}</h3><p>{ar?current.bodyAr:current.bodyFr}</p><a className="text-link" href="#carnet">{ar?'أحضّر إطلالتي':'Composer ma mise en beauté'}<ArrowUpRight size={17}/></a></div></div></div></section>
  <BridalPlanner key={locale} locale={locale}/>
 </>}
 </>;
}

