'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {ArrowUpRight,ArrowDown} from 'lucide-react';
import BridalPortrait from './BridalPortrait';
import BridalFilm from './BridalFilm';
import BridalPlanner from './BridalPlanner';
import Reveal from './Reveal';

function Spark({className=''}:{className?:string}){return <svg className={`bridal-spark ${className}`} viewBox="0 0 40 40" aria-hidden="true"><path d="M20 0C22 14 26 18 40 20C26 22 22 26 20 40C18 26 14 22 0 20C14 18 18 14 20 0Z" fill="currentColor"/></svg>}
const stories=[
 {image:'bridal-updo',fr:'La coiffure',ar:'التسريحة',titleFr:'La coiffure, avec votre tenue.',titleAr:'حركة ناعمة. بصمتكِ.',bodyFr:'Une attache délicate, du volume ou des longueurs libres. Partagez vos inspirations, votre tenue et vos accessoires pour imaginer l’ensemble avec Siham.',bodyAr:'رفعة ناعمة، حجم أو خصلات منسدلة. شاركي صور إلهامكِ وإطلالتكِ وإكسسواراتكِ لتتخيّلي التفاصيل مع سهام.',altFr:'Chignon de cérémonie avec accessoires floraux, archive du salon',altAr:'رفعة شعر لمناسبة مع إكسسوارات زهرية من أرشيف الصالون'},
 {image:'bridal-makeup-stock',fr:'Le maquillage',ar:'المكياج',titleFr:'Le maquillage, selon vos envies.',titleAr:'جمالكِ، كما تحبّينه.',bodyFr:'Teint lumineux, regard soutenu ou lèvres dessinées : montrez vos inspirations à Siham, ainsi que les effets que vous préférez éviter.',bodyAr:'نظرة، إشراقة ولون. أخبرينا بما تحبّينه وما تفضّلين تجنّبه. من هذا الحوار تبدأ إطلالتكِ.',altFr:'Inspiration : portrait de mariée et maquillage lumineux',altAr:'صورة إلهام: بورتريه عروس بمكياج مضيء'},
 {image:'bridal-details-stock',fr:'Les détails',ar:'التفاصيل',titleFr:'Voile, bijoux et finitions.',titleAr:'تفاصيل تبقى في الذاكرة.',bodyFr:'Apportez une photo du voile, des bijoux et du décolleté de votre tenue. Ces éléments aident à discuter de la coiffure et des finitions.',bodyAr:'زينة للشعر، ملمس خصلة وتناسق الإطلالة. شاركي التفاصيل التي تهمّكِ، فهي ما يمنح لحظتكِ طابعها الخاص.',altFr:'Inspiration : perles, voile de dentelle et manucure de mariée',altAr:'صورة إلهام: لؤلؤ وطرحة دانتيل وأظافر العروس'}
];
export default function BridalExperience({locale,full=false}:{locale:'fr'|'ar';full?:boolean}){
 const ar=locale==='ar';const [vertical,setVertical]=useState(true);const [active,setActive]=useState(0);const current=stories[active];
 useEffect(()=>{const screen=matchMedia('(min-width:1001px)');const update=()=>setVertical(screen.matches);update();screen.addEventListener('change',update);return()=>screen.removeEventListener('change',update)},[]);
 useEffect(()=>{const value=Number(new URLSearchParams(location.search).get('inspiration'));if(Number.isInteger(value)&&value>=0&&value<3)setActive(value)},[locale]);
 const selectInspiration=(index:number)=>{setActive(index);const url=new URL(location.href);url.searchParams.set('inspiration',String(index));history.replaceState(null,'',url)};
 return <>
 <section className={`bridal-editorial ${full?'is-full':'is-teaser'}`} data-scroll-key="bridal">
  <div className="bridal-orbit" aria-hidden="true"/><Spark className="spark-one"/><Spark className="spark-two"/>
  <Reveal className="bridal-editorial-copy"><p className="eyebrow">{ar?'سهام · لحظتكِ الأجمل':'SIHAM · VOTRE PLUS BEAU OUI'}</p>{full?<h1>{ar?<>أنتِ،<br/><em>ولا أحد سواكِ.</em></>:<>Vous.<br/><em>Et personne d’autre.</em></>}</h1>:<h2>{ar?<>أنتِ،<br/><em>بإطلالة لا تُنسى.</em></>:<>Vous, en<br/><em>inoubliable.</em></>}</h2>}<p className="bridal-lead">{ar?'جمال يشبهكِ، حتى أدقّ التفاصيل. لنتخيّل معاً الإطلالة التي ستحكين بها قصّتكِ.':'Une beauté qui vous ressemble, jusque dans les détails. Imaginons ensemble l’allure qui racontera votre histoire.'}</p><Link className="button" href={full?'#carnet':`/${locale}/mariee`}>{ar?(full?'لنتخيّل إطلالتي':'اكتشفي عالم العروس'):(full?'Imaginer ma mise en beauté':'Découvrir l’univers mariée')}<ArrowUpRight size={18}/></Link>{full&&<a className="bridal-explore" href="#inspirations">{ar?'أتصفّح الإلهام':'Feuilleter les inspirations'}<ArrowDown size={15}/></a>}<span className="bridal-handwriting">{ar?'للحظات التي تبقى.':'Pour les instants qui restent.'}</span></Reveal>
  <Reveal className="bridal-editorial-visual bridal-film-visual" delay={150}><BridalFilm locale={locale}/><div className="bridal-memory-strip"><figure><BridalPortrait locale={locale}/><figcaption>{ar?'إطلالة من أرشيف الصالون':'Une allure des archives'}</figcaption></figure><figure><img src="/media/bridal-updo.webp" width="480" height="640" alt={ar?'تفاصيل رفعة شعر زهرية':'Détail d’un chignon fleuri'} loading="lazy"/><figcaption>{ar?'التفاصيل التي تكمل الإطلالة':'Le sens du détail'}</figcaption></figure></div></Reveal>
 </section>
 {full&&<>
  <section className="bridal-album section" id="inspirations" data-scroll-key="bridal-inspirations"><Reveal className="album-heading"><p className="eyebrow">{ar?'دفتر الإلهام':'LE CARNET D’INSPIRATIONS'}</p><h2>{ar?'إطلالة واحدة. ألف تفصيل.':<>Une allure.<br/><em>Mille nuances.</em></>}</h2><p>{ar?'أعمال من الصالون وصور للإلهام، لتتخيّلي ما يشبهكِ.':'Créations de la maison et images d’inspiration : un carnet pour affiner vos envies.'}</p></Reveal><div className="album-layout"><div className="album-choices" role="tablist" aria-label={ar?'إلهام العروس':'Inspirations mariée'} aria-orientation={vertical?'vertical':'horizontal'}>{stories.map((s,i)=><button role="tab" id={`inspiration-tab-${i}`} aria-controls="inspiration-panel" aria-selected={active===i} tabIndex={active===i?0:-1} key={s.image} onClick={()=>selectInspiration(i)} onKeyDown={e=>{if(['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(active+((e.key==='ArrowDown'||e.key===(ar?'ArrowLeft':'ArrowRight'))?1:2))%3;selectInspiration(n);document.getElementById(`inspiration-tab-${n}`)?.focus()}}}><span>0{i+1}</span><span>{ar?s.ar:s.fr}</span><ArrowUpRight size={22}/></button>)}</div><div className="album-panel" id="inspiration-panel" role="tabpanel" aria-labelledby={`inspiration-tab-${active}`} tabIndex={0}><figure key={current.image}><img src={`/media/${current.image}.webp`} alt={ar?current.altAr:current.altFr} width="800" height="1000" loading="lazy"/><figcaption>OHH ZAZ · {active===0?(ar?'من أرشيف الدار':'ARCHIVES DE LA MAISON'):(ar?'صورة للإلهام · ليست من أعمال الصالون':'IMAGE D’INSPIRATION · HORS RÉALISATIONS DU SALON')}</figcaption></figure><div className="album-story" key={current.fr}><Spark/><h3>{ar?current.titleAr:current.titleFr}</h3><p>{ar?current.bodyAr:current.bodyFr}</p><Link className="text-link" href={`/${locale}/contact`}>{ar?'أشارك رغباتي':'Partager mes envies'}<ArrowUpRight size={17}/></Link></div></div></div></section>
  <BridalPlanner key={locale} locale={locale}/>
 </>}
 </>;
}

