'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import ContactAction from './ContactAction';
import {useSearchParams} from 'next/navigation';
import {categories as defaults,type Category} from '../data/services';
export default function PriceMenu({locale,categories=defaults}:{locale:'fr'|'ar';categories?:Category[]}){const ar=locale==='ar';const search=useSearchParams();const [filter,setFilter]=useState('all');useEffect(()=>{const value=search.get('category');setFilter(categories.some(c=>c.id===value)?value!:'all')},[search]);const choose=(id:string)=>{setFilter(id);const u=new URL(location.href);if(id==='all')u.searchParams.delete('category');else u.searchParams.set('category',id);u.hash='tarifs';history.replaceState(null,'',u)};return <section className="section price-menu" id="tarifs" data-scroll-key="prices"><div className="section-heading"><div><p className="eyebrow">{ar?'اختاري لحظتكِ':'PRIX DU SALON'}</p><h2>{ar?'قائمة الجمال والأسعار':'Les prestations, en détail.'}</h2></div><span className="price-currency">{ar?'الأسعار بالدرهم المغربي':'Tarifs en dirhams marocains'}</span></div><div className="price-filters" role="group" aria-label={ar?'تصفية حسب الخدمة':'Filtrer par catégorie'}>{[{id:'all',fr:'Tout voir',ar:'الكل'},...categories].map(c=><button type="button" key={c.id} aria-pressed={filter===c.id} onClick={()=>choose(c.id)}>{c[locale]}</button>)}</div><div className="price-groups">{categories.filter(c=>filter==='all'||filter===c.id).map(c=><section key={c.id} className="price-group" data-scroll-key={`prices-${c.id}`} aria-labelledby={`category-${c.id}`}><h3 id={`category-${c.id}`}>{c[locale]}</h3><dl>{c.items.map(s=><div className="price-row" key={s.fr}><dt><img className="tariff-image" src={`/media/services/${s.image||({coiffure:'brushing',onglerie:'ongles',maquillage:'maquillage',epilation:'epilation',soins:'visage'}[c.id]||'visage')}-thumb.webp`} alt="" width="68" height="80" loading="lazy"/><span>{s[locale]}{s.minutes&&<small>{s.minutes} {ar?'دقيقة':'min'}</small>}{s.alternative&&<small>{ar?'يُحدّد الخيار مع الصالون':'Option à préciser avec le salon'}</small>}</span></dt><dd>{s.from&&<span>{ar?'ابتداءً من':'À partir de'} </span>}<bdi>{s.price}{s.alternative?` / ${s.alternative}`:''} {ar?'د.م.':'DH'}</bdi><ContactAction platform="whatsapp" locale={locale} className="tariff-enquiry" message={ar?`مرحباً، بغيت نسول على خدمة ${s.ar}.`:`Bonjour, je souhaite me renseigner sur la prestation ${s.fr}.`}><span className="sr-only">{ar?`السؤال عن ${s.ar}`:`Demander ${s.fr}`}</span></ContactAction></dd></div>)}</dl></section>)}</div><div className="price-end"><p>{ar?'لإطلالة العروس أو لطلب خاص، شاركي رغباتكِ مع سهام.':'Pour une mise en beauté mariée ou une demande particulière, partagez vos envies avec Siham.'}</p><Link className="button" href={`/${locale}/contact`}>{ar?'لنتحدث عنكِ':'Parlons de vous'} <ArrowUpRight size={17} aria-hidden="true"/></Link></div></section>}

