'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Star,ArrowUpRight,PenLine,Check} from 'lucide-react';
import {business} from '../data/business';
type Review={id:string;name:string;rating:number;comment:string;created_at:string};
export default function Reviews({locale}:{locale:'fr'|'ar'}){
 const ar=locale==='ar',t=(fr:string,arabic:string)=>ar?arabic:fr;
 const [data,setData]=useState<{reviews:Review[];count:number;average:number|null}|null>(null),[unavailable,setUnavailable]=useState(false),[open,setOpen]=useState(false),[rating,setRating]=useState(0),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/reviews',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();setData(await r.json())}).catch(e=>{if(e.name!=='AbortError')setUnavailable(true)});return()=>controller.abort()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!rating)return;const fields=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:fields.get('name'),comment:fields.get('comment'),website:fields.get('website'),consent:fields.get('consent')==='on',rating,locale}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(r.status===429?'limit':'unavailable');setSent(true)}catch(e){setError(e instanceof Error&&e.message==='limit'?t('Veuillez réessayer demain.','حاولي غداً من فضلكِ.'):t('Envoi impossible. Votre texte reste ici, réessayez.','تعذّر الإرسال. النص محفوظ هنا، حاولي مرة أخرى.'))}finally{setBusy(false)}}
 return <section className="section salon-reviews" id="avis" data-scroll-key="reviews"><div className="reviews-heading"><div><p className="eyebrow">{t('APRÈS VOTRE VISITE','بعد زيارتكِ')}</p><h2>{t('Vos mots,','كلماتكِ،')}<br/><em>{t('une part de la maison.','جزء من حكايتنا.')}</em></h2><p>{t('Un geste apprécié, un moment retenu, une attention à améliorer. Racontez-nous votre expérience au salon.','تفصيل أحببتِه أو اقتراح للزيارة المقبلة. أخبرينا عن تجربتكِ في الصالون.')}</p></div><div className="reviews-summary">{data&&data.count>0?<><strong>{data.average?.toLocaleString(ar?'ar-MA':'fr-MA')}<small> / 5</small></strong><span>{data.count} {t('avis sur ce site','تقييم على هذا الموقع')}</span></>:<PenLine size={32} strokeWidth={1}/>}<button className="button" aria-expanded={open} aria-controls="review-form" onClick={()=>setOpen(v=>!v)}>{t('Partager mon expérience','أشارك تجربتي')}<PenLine size={17}/></button><a className="text-link" href={business.mapUrl} target="_blank" rel="noopener noreferrer">{t('Consulter les avis Google Maps','الآراء على خرائط Google')}<ArrowUpRight size={16}/></a><small>{t('Les avis du site sont distincts des avis Google.','آراء الموقع مستقلة عن تقييمات Google.')}</small></div></div>
 <div className="review-grid">{data?.reviews.map(r=><article className="review-card" key={r.id}><div className="review-stars" aria-label={`${r.rating} / 5`}>{[1,2,3,4,5].map(n=><Star key={n} size={15} fill={n<=r.rating?'currentColor':'none'} aria-hidden="true"/>)}</div><p className="review-quote" dir="auto">{r.comment}</p><div className="review-author"><span className="review-monogram" aria-hidden="true">{Array.from(r.name)[0]}</span><div><strong dir="auto">{r.name}</strong><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleDateString(ar?'ar-MA':'fr-MA',{month:'long',year:'numeric'})}</time></div></div><small>{t('Avis du site · visite non vérifiée','رأي على الموقع · الزيارة غير موثّقة')}</small></article>)}</div>
 <p role="status">{unavailable?t('Avis momentanément indisponibles. Consultez Google Maps.','الآراء غير متاحة مؤقتاً. يمكنكِ مراجعة Google Maps.'):data?.count===0?t('Soyez la première à partager votre expérience ici.','كوني أول من يشارك تجربته هنا.'):!data?t('Chargement des avis…','جارٍ تحميل الآراء…'):''}</p>
 {open&&<div id="review-form" className="review-form-shell">{sent?<div role="status"><Check size={32}/><h3>{t('Merci pour vos mots.','شكراً على كلماتكِ.')}</h3><p>{t('Votre avis a été reçu. Il sera examiné avant publication.','وصل رأيكِ وهو قيد المراجعة قبل نشره.')}</p></div>:<form onSubmit={submit}><h3>{t('Comment s’est passée votre visite ?','كيف كانت زيارتكِ؟')}</h3><fieldset disabled={busy}><legend>{t('Votre note','تقييمكِ')}</legend><div className="rating-picker">{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name="rating" value={n} checked={rating===n} onChange={()=>setRating(n)} required/><Star size={28} fill={n<=rating?'currentColor':'none'}/><span className="sr-only">{n} / 5</span></label>)}</div></fieldset><label>{t('Nom affiché','الاسم الذي سيظهر')}<input name="name" autoComplete="given-name" required minLength={2} maxLength={60} disabled={busy}/></label><label>{t('Votre expérience','تجربتكِ')}<textarea name="comment" required minLength={20} maxLength={1500} rows={4} disabled={busy}/></label><label className="review-trap" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="review-consent"><input name="consent" type="checkbox" required disabled={busy}/><span>{t('J’accepte la publication de mon nom, de ma note et de mon commentaire après modération. Je n’inclus pas de données privées concernant autrui.','أوافق على نشر اسمي وتقييمي ونص رأيي بعد المراجعة، دون تضمين بيانات خاصة بالآخرين.')} <a href={`/${locale}/mentions-legales`}>{t('Confidentialité','الخصوصية')}</a></span></label><p className="review-policy">{t('Avis positifs et négatifs bienvenus. Nous modérons les abus, publicités et données privées, sans modifier votre note.','نرحّب بالآراء الإيجابية والسلبية. نراجع الإساءة والإعلانات والبيانات الخاصة دون تغيير تقييمكِ.')}</p><button className="button" disabled={busy}>{busy?t('Envoi…','جارٍ الإرسال…'):t('Envoyer mon avis','إرسال رأيي')}<ArrowUpRight size={17}/></button><p role="alert">{error}</p></form>}</div>}
 </section>
}
