import ContactAction from './ContactAction';
export default function SiteInformation({locale}:{locale:'fr'|'ar'}) {
 const ar=locale==='ar';
 const sections=ar?[
  ['الموقع والتواصل','هذا الموقع يقدّم صالون OHH ZAZ by SIHAM في الدار البيضاء. طوّره Naoufal Laamouri. لأي سؤال حول محتوى الموقع أو خصوصيتكِ، تواصلي مباشرة مع الصالون.'],
  ['طلبات الموعد والمنتجات','الأسعار بالدرهم المغربي. الأسعار التي تحمل «ابتداءً من» تتغيّر حسب الخدمة؛ أكّدي المبلغ والتوفّر مع الصالون. دفتر العروس يحضّر رسالة فقط ولا يؤكّد الحجز. لا يوجد دفع إلكتروني؛ معاينات المنتجات القادمة ليست عروضاً للبيع.'],
  ['المعلومات المخزّنة على جهازكِ','يُحفظ دفتر العروس مؤقتاً في جلسة المتصفّح لتبقى اختياراتكِ عند التنقّل أو تغيير اللغة. لا يُرسل إلى خادم الموقع. فتح واتساب يمرّر نصّ الرسالة إلى واتساب؛ أنتِ تختارين إرسالها. يُحفظ كذلك موضع الصفحة مؤقتاً عند تغيير اللغة.'],
  ['الحسابات والاستضافة','دخول الإدارة مخصّص للموظفين المصرّح لهم. يُستخدم ملف ارتباط ضروري وآمن للجلسة لمدة تصل إلى ثماني ساعات. تُخزّن بصمات كلمات المرور والجلسات، ولا تُخزّن كلمات المرور المقروءة. يستضيف Netlify الموقع، وتستضيف Railway قاعدة البيانات، ويدير Cloudflare اسم النطاق. قد تعالج خدمات الاستضافة بيانات اتصال تقنية لتشغيل الموقع وحمايته.'],
  ['روابط خارجية','روابط واتساب وإنستغرام وتيك توك وخرائط Google تفتح خدمات مستقلة تخضع لسياسات خصوصيتها. لا يضمّن الموقع أدوات إعلانات أو تحليلات تسويقية.'],
  ['حقوق النشر','حقوق العمل الأصلي في هذا الموقع محفوظة لـ OHH ZAZ by SIHAM وNaoufal Laamouri. لا يُسمح بإعادة استعمال الشيفرة أو التصميم أو النصوص الأصلية دون إذن. تخضع البرامج والخطوط والصور الخارجية لتراخيص أصحابها. صور الإلهام لا تمثّل بالضرورة أعمال الصالون.']
 ]:[
  ['Le site et vos demandes','Ce site présente OHH ZAZ by SIHAM, salon de beauté à Casablanca. Il est développé par Naoufal Laamouri. Pour une question sur le contenu ou vos données, contactez directement le salon.'],
  ['Rendez-vous, tarifs et produits','Les prix sont indiqués en dirhams marocains. Un tarif « à partir de » dépend de la prestation : confirmez le montant et la disponibilité avec le salon. Le carnet mariée prépare une demande, sans réserver de créneau. Aucun paiement en ligne n’est proposé. Les aperçus de futurs produits ne constituent pas des offres de vente.'],
  ['Ce qui reste dans votre navigateur','Votre carnet mariée est conservé temporairement dans la session du navigateur pour retrouver vos choix après navigation ou changement de langue. Il n’est pas envoyé au serveur du site. Ouvrir WhatsApp transmet le texte préparé à WhatsApp ; vous choisissez ensuite de l’envoyer. La position dans la page est également conservée temporairement lors du changement de langue.'],
  ['Comptes et hébergement','L’administration est réservée au personnel autorisé. Elle utilise un cookie de session nécessaire, sécurisé, d’une durée maximale de huit heures. Les mots de passe et jetons de session sont conservés sous forme de hachages, jamais en clair. Le site est hébergé par Netlify, sa base de données par Railway et son domaine est géré par Cloudflare. Les hébergeurs peuvent traiter des données techniques de connexion pour faire fonctionner et protéger leurs services.'],
  ['Services externes','Les liens WhatsApp, Instagram, TikTok et Google Maps ouvrent des services indépendants soumis à leurs propres politiques de confidentialité. Ce site n’intègre pas de traceur publicitaire ni d’outil d’analyse marketing.'],
  ['Droits sur le site','Le travail original du site appartient à OHH ZAZ by SIHAM et à Naoufal Laamouri. Sa reproduction ou réutilisation nécessite une autorisation. Les logiciels, polices et photographies de tiers restent soumis à leurs licences respectives. Les images d’inspiration ne sont pas présentées comme des réalisations du salon.']
 ];
 return <section className="section site-information page-start" data-scroll-key="information"><p className="eyebrow">OHH ZAZ · BY SIHAM</p><h1>{ar?'الخصوصية وحقوق الموقع':'Confidentialité & droits du site'}</h1>{sections.map(([title,body])=><article key={title}><h2>{title}</h2><p>{body}</p></article>)}<ContactAction platform="whatsapp" locale={locale} className="button">{ar?'تواصلي مع الصالون':'Contacter le salon'}</ContactAction></section>;
}
