import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
import StructuredData from '../../../components/StructuredData';
import Salon from '../../../components/Salon';
import {getCatalogue} from '../../../lib/catalogue-server';
import {routes,pathFor} from '../../../lib/site';
const titles={fr:['Salon de beauté à Casablanca','La mariée','Prestations & tarifs','Cosmétiques & accessoires','Le salon','Contact & rendez-vous'],ar:['صالون الجمال في الدار البيضاء','العروس','الخدمات والأسعار','مستحضرات وأجهزة الجمال','الصالون','التواصل والمواعيد']};
const descriptions={fr:['Coiffure, coloration, onglerie et maquillage chez OHH ZAZ by SIHAM à Casablanca. Consultez les tarifs et préparez votre visite.','Coiffure, maquillage et détails de votre mise en beauté mariée. Préparez vos inspirations et votre demande avec Siham.','Les tarifs du salon en dirhams : coiffure, coloration, manucure, maquillage, épilation, soins du visage.','Cosmétiques, soins capillaires, brosses et sèche-cheveux : explorez la sélection OHH ZAZ à Casablanca par catégorie. Renseignements sur WhatsApp.','Découvrez les espaces réels du salon OHH ZAZ à Casablanca, ses horaires et son itinéraire.','Contactez OHH ZAZ by SIHAM sur WhatsApp ou Instagram pour vos prestations et disponibilités. Horaires et itinéraire à Casablanca.'],ar:['الشعر والصبغات والأظافر والمكياج في OHH ZAZ by SIHAM بالدار البيضاء. اكتشفي الأسعار وحضّري زيارتكِ.','تسريحة العروس ومكياجها وتفاصيل إطلالتها. حضّري صور إلهامكِ وطلبكِ مع سهام.','أسعار الشعر والصبغات والأظافر والمكياج وإزالة الشعر والعناية بالوجه بالدرهم المغربي.','مستحضرات التجميل والعناية بالشعر والفرش ومجففات الشعر في OHH ZAZ بالدار البيضاء. قلبي على اللي بغيتي وسولينا على واتساب.','اكتشفي فضاءات صالون OHH ZAZ الحقيقية بالدار البيضاء وأوقات العمل والاتجاهات.','تواصلي مع OHH ZAZ by SIHAM عبر واتساب أو إنستغرام للاستفسار عن الخدمات والمواعيد. أوقات العمل والاتجاهات في الدار البيضاء.']};
export async function generateMetadata({params}:{params:Promise<{locale:string;slug?:string[]}>}):Promise<Metadata>{const {locale,slug}=await params;const route=(slug||[]).join('/');const i=routes.indexOf(route);if(!['fr','ar'].includes(locale)||i<0)return {};const l=locale as 'fr'|'ar';const title=`${titles[l][i]} — OHH ZAZ by SIHAM`;const description=descriptions[l][i];return {title,description,alternates:{canonical:pathFor(l,route),languages:{'fr-MA':pathFor('fr',route),'ar-MA':pathFor('ar',route),'x-default':pathFor('fr',route)}},openGraph:{title,description,type:'website',siteName:'OHH ZAZ by SIHAM',locale:l==='fr'?'fr_MA':'ar_MA',alternateLocale:l==='fr'?'ar_MA':'fr_MA',url:pathFor(l,route),images:[{url:'/brand/social-sharing.jpg',width:1200,height:800,alt:'OHH ZAZ by SIHAM — Casablanca'}]},twitter:{card:'summary_large_image',title,description,images:['/brand/social-sharing.jpg']}}}
export default async function Page({params}:{params:Promise<{locale:string;slug?:string[]}>}){const {locale,slug}=await params;const route=(slug||[]).join('/');if(!['fr','ar'].includes(locale)||!routes.includes(route))notFound();const catalogue=await getCatalogue();return <><StructuredData contacts={catalogue.contacts} locale={locale as 'fr'|'ar'} page={route}/><Salon {...catalogue} locale={locale as 'fr'|'ar'} page={route}/></>;}
